### ISSUE TITLE
自适应好像不太行

### ISSUE THREAD

**Issue by lhlyu** [iCodek/vue-blog#1]
不同尺寸的屏幕字体大小，排版
![image](https://user-images.githubusercontent.com/41979509/91514391-345a2a80-e919-11ea-91db-3c5a2d14d356.png)

**Comment by iCodek** [comment]
确实，rem效果有点不太好。移动端会再写个适配的css。另外想请教下你这个多平台预览效果是怎么弄出来的。

**Comment by lhlyu** [comment]
以前我也是考虑用rem，根据屏幕尺寸动态计算根字体大小，效果不佳，后来我参考了一下B站的，屏幕小于700使用3.2vw作为基础字体大小，大于700的统一16px
那个是网站缩略图生成的，[链接](https://www.yangruolan.com/Web_slt/)

**Comment by iCodek** [comment]
多谢老哥，适配会马上跟上

**Comment by lhlyu** [comment]
我写过九次博客网站，效果都不理想，都删了，现在不敢写了，得想好再写
我打算等vue3正式版出来后再写个

**Comment by zty381309501** [comment]
> 我写过九次博客网站，效果都不理想，都删了，现在不敢写了，得想好再写
> 我打算等vue3正式版出来后再写个

大佬，你在哪呢？给我Q回复个消息吧
